### ISSUE TITLE
Enhancement: Allow configuration for uploading single files OR excludes/includes on folders

### ISSUE THREAD

**Issue by lkoe** [random-maven/bintray-maven-plugin#2]
Currently it is a bit complicated to upload a single file from an otherwise populated directory using this plugin.

Please check this setup: https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs-updatesite/pom.xml

The second execution (`upload-update-site-archive`) uploads a single archive file to a different path in the Bintray repo. Since the archive file is being created in a directory containing other stuff as well I cannot upload it directly, since the plugin only allows for configuration of source folders, which are uploaded completely.

So in order to make it work for this case I needed an additional Ant task, which copies the single file to a new directory, which is then uploaded.

My setup would be less complicated if the plugin either allowed for configuration of single source files OR for configuration of the typical exclude/include mechanics for the source folder.

**Comment by Andrei-Pozolotin** [comment]
ok, thinking

**Comment by Andrei-Pozolotin** [comment]
1. here is logic

https://random-maven.github.io/bintray-maven-plugin/upload-mojo.html#uploadRegex

https://github.com/random-maven/bintray-maven-plugin/blob/master/src/main/scala/com/carrotgarden/maven/bintray/UploadMojo.scala#L102

2. try 1.3.x

https://bintray.com/random-maven/maven/bintray-maven-plugin

**Comment by Andrei-Pozolotin** [comment]
resolved by 
https://github.com/random-maven/bintray-maven-plugin/releases/tag/1.3.20180612164212
