### ISSUE TITLE
Enhancement: Add functionality and configuration option to clean a Bintray target folder before uploading

### ISSUE THREAD

**Issue by lkoe** [random-maven/bintray-maven-plugin#3]
When needing to re-spin a release, the release files (a P2 repository) get new timestamps in their file names.

When uploading the files as is, the previously uploaded files stay in the Bintray repository and need to be manually removed (which is somewhat cumbersome).

An idea for enhancement of this plugin would be to add code and configuration option to optionally clean the upload target folder before uploading OR to have an addition new `clean` goal.

**Comment by Andrei-Pozolotin** [comment]
ok, thinking

**Comment by Andrei-Pozolotin** [comment]
1. new logic

https://random-maven.github.io/bintray-maven-plugin/upload-mojo.html#performCleanup

2. try 1.3.x

https://bintray.com/random-maven/maven/bintray-maven-plugin

**Comment by Andrei-Pozolotin** [comment]
resolved by 
https://github.com/random-maven/bintray-maven-plugin/releases/tag/1.3.20180612164212
