### ISSUE TITLE
Usage question - how is bintray package name determined?

### ISSUE THREAD

**Issue by padamstx** [random-maven/bintray-maven-plugin#8]
I've been struggling to find a reliable way to deploy the artifacts from a multi-module maven project to a bintray repository such that I can also mirror those artifacts to JCenter (and eventually to maven central).   The jcenter requirement apparently comes at a cost... for the jcenter mirroring to work, I apparently must deploy each module's files (pom, jar, etc.) to a module-specific package within my bintray repository.  Note that this one-module-per-bintray-package requirement is never mentioned in the multi-module maven example provided by bintray (ugh).

I've tried using the default maven-deploy-plugin but of course that causes all files associated with all my modules to be deployed to the single bintray repo and package that are identified in the repository URL specified in the distributionManagement section.   Unfortunately, that prevents me from being able to mirror/link the files to JCenter.

I was excited to discover this git repo with the bintray maven plugin.   I want to give it a try, but just curious... do you use the maven coordinates (e.g. <group-id>:<artifact-id>) to determine the name of the bintray package where each module's files should be uploaded?
And... do I need to pre-create the bintray package associated with each module in my project or will the plugin create bintray packages on the fly within the configured bintray repo?

Thanks in advance!

**Comment by Andrei-Pozolotin** [comment]
1. see if any of these tests address the question
https://github.com/random-maven/bintray-maven-plugin/tree/master/src/it

2. building a prototype project is is the only real answer
https://en.wikiquote.org/wiki/William_Blake
`The true method of knowledge is experiment`

**Comment by padamstx** [comment]
I have incorporated the use of bintray-maven-plugin and it is doing a fantastic job of deploying my artifacts to bintray repositories :)

**Comment by Andrei-Pozolotin** [comment]
great
